# Generated by Django 5.2.14 on 2026-05-23 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AthleticEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('event_type', models.CharField(choices=[('friendly', 'Amistoso'), ('tournament', 'Torneio'), ('tryout', 'Seletiva'), ('meeting', 'Reuniao')], max_length=20)),
                ('date', models.DateTimeField()),
                ('place', models.CharField(max_length=120)),
                ('status', models.CharField(max_length=80)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='BoardTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100)),
                ('task', models.CharField(max_length=180)),
                ('owner', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('in_progress', 'Em andamento'), ('done', 'Concluido')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['status', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(max_length=80)),
                ('weekday', models.CharField(max_length=80)),
                ('time', models.TimeField()),
                ('place', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sport', 'weekday'],
            },
        ),
    ]
