# Generated by Django 5.2.14 on 2026-05-23 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampusBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('block_type', models.CharField(max_length=120)),
                ('floor_info', models.CharField(max_length=80)),
                ('map_position', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CampusRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('floor', models.CharField(max_length=40)),
                ('room_type', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='campus.campusblock')),
            ],
            options={
                'ordering': ['block__code', 'floor', 'name'],
            },
        ),
    ]
